[tool.black]
line-length = 108
target-version = ["py311"]
exclude = '''
/(
    \.venv|
    old_soft|
    old|
    \.git|
    \.mypy_cache|
    \.pytest_cache|
    __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 108
skip = [".venv", "old_soft", "old"]
